theme: theme-jekyll-midnight
title: Ecologial Data Analysis 2019 Bonus Material
description: All the things you never thought you wanted to know about using R and making ggplot graphics for your EDA assignments, and links to useful pages around the web.
